name: Create Release

on:
  push:
    tags:
      - 'v*' # 触发条件：推送以v开头的标签，如 v0.4

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.get_version.outputs.VERSION }}
          path: ./README.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## What's Changed
            ${{ steps.changelog_reader.outputs.changes }}
            
            ## Installation
            1. Install [Tampermonkey](https://www.tampermonkey.net/) or other userscript manager
            2. [Click here to install](https://github.com/landrarwolf/youtube-speed-control/releases/download/${{ steps.get_version.outputs.VERSION }}/youtube-speed-control.user.js)
          files: |
            youtube-speed-control.user.js
            LICENSE
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 