---
name: Create Release

'on':
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Extract changelog
        id: extract_changelog
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          # Extract changelog for the specific version
          CHANGELOG=$(awk '/- \*\*'"${VERSION}"'\*\*/{p=NR+2}(NR<=p){print}' \
            README.md)
          # Output to GITHUB_OUTPUT
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Validate release assets
        run: |
          # Ensure required files exist
          if [ ! -f "youtube-speed-control.user.js" ]; then
            echo "Error: youtube-speed-control.user.js not found"
            exit 1
          fi

          if [ ! -f "LICENSE" ]; then
            echo "Error: LICENSE file not found"
            exit 1
          fi

          echo "✅ All required release assets found"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            # Changelog
            ${{ steps.extract_changelog.outputs.CHANGELOG }}

            # Installation
            1. Install [Tampermonkey](https://www.tampermonkey.net/) or
               other userscript manager
            2. [Install Script](
               https://github.com/landrarwolf/youtube-speed-control/
               releases/download/${{ steps.get_version.outputs.VERSION }}/
               youtube-speed-control.user.js)
          files: |
            youtube-speed-control.user.js
            LICENSE
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
